apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demo-data-catalog
  namespace: flux-demo
  labels:
    kommander.d2iq.io/gitapps-gitrepository-type: catalog
    kommander.d2iq.io/gitrepository-type: catalog
spec:
  interval: 10s
  ref:
    branch: master
  url: https://github.com/swiftsuretech/dkp_datacatalog.git
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-catalog-cluster
rules:
- apiGroups: ["rbac.authorization.k8s.io", "admissionregistration.k8s.io", "apiextensions.k8s.io", "policy", "storage.k8s.io", "ceph.rook.io"]
  resources: ["clusterroles", "clusterrolebindings", "validatingwebhookconfigurations", "customresourcedefinitions", "rolebindings", "podsecuritypolicies", "storageclasses", "cephclusters"]
  verbs:
  - "*"
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-catalog-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: data-catalog-cluster
subjects:
- kind: ServiceAccount
  name: data-project
  namespace: data-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-catalog
  namespace: flux-demo
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-catalog
  namespace: flux-demo
subjects:
  - kind: ServiceAccount
    name: data-project
    namespace: data-project
  - kind: ServiceAccount
    name: nifikop
    namespace: data-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-catalog
